### ISSUE TITLE
Buffer showing strange characters

### ISSUE THREAD

**Issue by SpeedBird95** [DonEduardo/SprinklerControl#1]
Hello , I set up the ESP to connect to an AP and get no problems or any errors.

However when I do a GET request or log into the IP of the unit the stored buffer shows a strange character.

Here is the code:

`
char buf[500];
  int iLen = wifi.ReceiveMessage(buf);
  
  if(iLen > 0)
  {
      DebugSerial.println("Your buffer:");
      DebugSerial.println("------------");
      DebugSerial.print(buf);
      DebugSerial.println("\n------------");

Here is the debug response : 
`
AT+RST
Module is ready
AT+CWMODE=1
AT+RST
reboot wifi is OK
AT+CWJAP="DrayTek","Password"
AT+CIFSR
192.168.100.67OK
AT+CIPMUX=1
AT+CIPSERVER=1,80
Server is set up
<--- Here is where I type http://IP/?status1=1
IPD,0,419:GET /?status1=1 HTTP/1.1
Host: 192.168.100.67
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KTL ieGek)Crm/4..2216Sfr/3.6
cet tx/tlplcto/hm+m,plcto/lq09iaewpiaean,*q08
cp-ndn:gi elt
ce-aga:e-,nq.

KYour buffer:
------------
⸮
------------
AT+CIPSEND=0,117
AT+CIPCLOSE=0
`

**Comment by DonEduardo** [comment]
I don't think you are using the code I uploaded because my code does not accept HTTP GET commands.  It only accepts a direct connection, like with telnet or from the Android App I uploaded that opens a socket. Having said that, I don't use the ESP8266 in this way anymore. I program it directly using the Arduino IDE instead of connecting it serially to another Arduino. I may do an update on this project in a couple months showing how to do that but I think there are already people showing how to do it.
